on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - 1.79.0
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: rustup run ${{ matrix.rust }} cargo clippy --all --all-targets --all-features -- -D warnings

  fmt:
    name: Rustfmt
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          # Once we settle on a MSRV we should add that here.
          - 1.79.0
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt
      - run: rustup run ${{ matrix.rust}} cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          # Once we settle on a MSRV we should add that here.
          - 1.79.0
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
      - run: rustup run ${{ matrix.rust }} cargo test --all-features

  typeshare:
    name: Typeshare
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        rust:
          - 1.79.0
        lang:
          - typescript
          - kotlin
          - swift
        include:
          - fs: ts
            lang: typescript
          - fs: kt
            lang: kotlin
          - fs: swift
            lang: swift
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4
      - uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc #v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: clechasseur/rs-cargo@34eb9ee3e4186e5c7820a54393fbf081f78bc102 #v2
        with:
          command: install
          args: --version 1.7.0 --locked typeshare-cli
      - run: typeshare --lang=${{ matrix.lang }} . -o test.${{ matrix.fs }}
